version: '3.7'

networks:
  TEST:
    ipam:
      config:
        - subnet: 172.70.0.0/24

services:
  master:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./master/default.conf:/etc/nginx/conf.d/default.conf 
    networks:
      TEST:
        ipv4_address: 172.70.0.2
  slave_1:
    depends_on:
       - master
    image: nginx:alpine
    ports:
      - "8001:80"
    volumes:
      - ./slave1/index.html:/usr/share/nginx/html/index.html
    networks:
      TEST:
        ipv4_address: 172.70.0.3
  slave_2:
    depends_on:
       - master
    image: nginx:alpine
    ports:
      - "8002:80"
    volumes:
      - ./slave2/index.html:/usr/share/nginx/html/index.html
    networks:
      TEST:
        ipv4_address: 172.70.0.4
  slave_3:
    depends_on:
       - master
    image: nginx:alpine
    ports:
      - "8003:80"
    volumes:
      - ./slave3/index.html:/usr/share/nginx/html/index.html
    networks:
      TEST:
        ipv4_address: 172.70.0.5

